# Provides a setup of external dependencies for
# usage on a local development environment.
#
# Start with the command `docker compose -f local-deps.yaml up -d`.
# Stop with the command `docker compose -f local-deps.yaml stop`.

services:
  postgresql:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    ports:
      - 5432:5432

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopassword
    command: server /data --console-address ':9090'
    ports:
      - 9000:9000
      - 9090:9090
